from typing import Any, Dict, List, Tuple
from django.db.backends.base.introspection import (BaseDatabaseIntrospection as BaseDatabaseIntrospection,
                                                   TableInfo as TableInfo, FieldInfo as FieldInfo)
from django.db.backends.utils import CursorWrapper

class DatabaseIntrospection(BaseDatabaseIntrospection):
    data_types_reverse: Dict = ...
    def get_field_type(self, data_type: Any, description: Any) -> str: ...
    def get_table_list(self, cursor: CursorWrapper) -> List[TableInfo]: ...
    def get_sequences(self, cursor: CursorWrapper, table_name: str, table_fields: Any = ...) -> List[Dict[str, str]]: ...
    def get_key_columns(self, cursor: CursorWrapper, table_name: str) -> List[Tuple[str, str, str]]: ...
    def get_primary_key_column(self, cursor: CursorWrapper, table_name: str) -> str: ...
    def get_constraints(self, cursor: CursorWrapper, table_name: str) -> Dict[str, Dict[str, Any]]: ...

    def get_table_description(self, cursor: CursorWrapper, table_name: str) -> List[FieldInfo]: ...
    def get_relations(self, cursor: CursorWrapper, table_name: str): ...
